# frozen_string_literal: true

source "https://rubygems.org"

gem "rails"
gem "pg", "~> 1.1"
gem "bootsnap", require: false

group :development, :test do
   gem 'rubocop', require: false
   gem 'ruby-lint', require: false
   gem 'ruby-lsp', require: false
end
gem "rubocop-rails", "~> 2.34"

gem "rubocop-performance", "~> 1.26"
#gem 'rails', '~> 7.1.3'
gem "rubocop-rake", "~> 0.7.1"

gem "rubocop-rspec", "~> 3.9"

gem "puma", "~> 8.0"

gem "brakeman", "~> 8.0", :groups => [:development, :test]
gem "bundler-audit", "~> 0.9.3", :groups => [:development, :test]
