# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.4.8'

gem 'bootsnap', require: false
gem 'pg', '~> 1.1'
gem 'rails'

group :development, :test do
  gem 'rswag-specs'
  gem 'rubocop', require: false
  gem 'ruby-lint', require: false
  gem 'ruby-lsp', require: false
end

gem 'rubocop-rails', '~> 2.34'

gem 'rubocop-performance', '~> 1.26'
# gem 'rails', '~> 7.1.3'
gem 'rubocop-rake', '~> 0.7.1'

gem 'rubocop-rspec', '~> 3.9'

gem 'bcrypt', '~> 3.1.7'

gem 'puma', '~> 8.0'

gem 'brakeman', '~> 8.0', groups: %i[development test]
gem 'bundler-audit', '~> 0.9.3', groups: %i[development test]

gem 'factory_bot_rails', group: %i[development test]
gem 'faker', group: %i[development test]
gem 'rspec-rails', group: %i[development test]
gem 'shoulda-matchers', group: [:test]

gem 'rswag-api'
gem 'rswag-ui'
