name: Lint Ruby Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.8"
          bundler-cache: true
          working-directory: ./api

      - name: Run RuboCop
        working-directory: ./api
        run: bundle exec rubocop --color
